# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{has_followers}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Fabiano Almeida}]
  s.date = %q{2012-01-24}
  s.description = %q{Add followers support to Rails 3 apps}
  s.email = %q{fabianoalmeida@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/models/follow.rb",
    "has_followers.gemspec",
    "lib/generators/has_followers.rb",
    "lib/generators/has_followers/migration/migration_generator.rb",
    "lib/generators/has_followers/migration/templates/create_has_followers_tables.rb",
    "lib/has_followers.rb",
    "lib/has_followers/engine.rb",
    "lib/has_followers/has_followers.rb",
    "spec/has_followers_spec.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/fabianoalmeida/has_followers}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.9}
  s.summary = %q{Add followers support to Rails 3 apps}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

